#--data file name--
SAMPLE:  ['BROAD_h19_maf_alsID'] #change to your file name 
#SAMPLE: ['ftd_gsa_step0','ftd_neurox_phaseII_step0', 'ftd_neurox_phaseIII_step0', 'ftd_neurox_phaseI_step0_hg19' ]
CHROMOSOMES: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22] 
BIMFILE: True

#--missingness--
imissTh: 0.05
lmissTh: 0.01
mind: "0.05"
geno: "0.01"

#--relatedness-- 
genome: "0.9"
highIBDTh: 0.9 #we don't exclude relatives, only duplicates and monozygotic twins
PI_HAT: "0.1" #to create a reltaives.txt file, no exclusion here

#--heterozygosity-- 
hetTh: 3

#--sex-- 
maleTh: 0.8
femaleTh: 0.2

#--minor allele frequency and HWE--
maf: "0.01" 
mafTh: 0.01
hwe: "1e-4"
hweTh: 1e-4
macTh: 20

#--european ancestry--
europeanTh: 10

